name: GNU/Linux
on:
  push:
    branches: [ "master", "unstable" ]
    paths:
      - rte/src/*
  pull_request:
    branches: [ "master", "unstable" ]
    paths:
      - rte/src/*
  workflow_dispatch:

jobs:
  gnu-linux:
    strategy:
      matrix:
        arch: [32, 64]
        build_type: [Release]
        include:
          - build_type: Release
            arch: 32
            release: ON
          - build_type: Release
            arch: 64
            release: ON

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Install 32-bit dependencies
        if: ${{ matrix.arch == 32 }}
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update

          # The Ubuntu 20.04 GitHub image adds a lot of unnecessary deb.sury.org packages,
          # which causes issues installing dependencies for SDL2 and SDL2-mixer.
          # Remove all that and downgrade to official versions.
          sudo apt-get remove --yes php.*
          sudo apt-get install --yes --allow-downgrades \
            libpcre2-16-0:amd64=10.34-7 \
            libpcre2-32-0:amd64=10.34-7 \
            libpcre2-8-0:amd64=10.34-7 \
            libpcre2-dev:amd64=10.34-7 \
            libpcre2-posix2:amd64=10.34-7

          sudo apt-get install -y \
            cmake \
            build-essential \
            gcc-multilib \
            g++-multilib \
            libsdl2-dev:i386 \
            libsdl2-image-dev:i386 \
            libsdl2-gfx-dev:i386 \
            libsdl2-mixer-dev:i386 \
            libsdl2-net-dev:i386

      - name: Install 64-bit dependencies
        if: ${{ matrix.arch == 64 }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            build-essential \
            g++-9 \
            gcc-multilib \
            g++-multilib \
            libc++-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-gfx-dev \
            libsdl2-mixer-dev \
            libsdl2-net-dev

      - name: Set compiler (gcc)
        run: |
          echo "CXX=g++" >> $GITHUB_ENV
          echo "CC=gcc" >> $GITHUB_ENV

      - name: Configure build
        env:
          ARCH: ${{ matrix.arch == 32 && '-DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32' || '' }}
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          cmake --version
          $CXX --version
          cd rte
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE $ARCH   \
                   -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=bin
          cp -r ../test/* bin

      - name: Build
        working-directory: rte/build
        run: |
          make

      - name: Package
        uses: actions/upload-artifact@v3
        with:
          name: "Brux-GNULinux-${{ matrix.arch }}-${{ matrix.build_type }}-binary"
          path: "rte/build/bin"
