name: Windows
on:
  push:
    branches: [ "master", "unstable" ]
    paths:
      - rte/src/*
  pull_request:
    branches: [ "master", "unstable" ]
    paths:
      - rte/src/*
  workflow_dispatch:

jobs:
  windows:
    strategy:
      matrix:
        arch: [x64]
        build_type: [Release]
        include:
          - build_type: Release
            arch: x64
            release: ON

    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          vcpkg integrate install
          vcpkg install sdl2:$Env:ARCH-windows
          vcpkg install sdl2-image:$Env:ARCH-windows
          vcpkg install sdl2-mixer:$Env:ARCH-windows

      - name: Install SDL2_image
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          mkdir manual
          cd manual
          C:\msys64\usr\bin\wget.exe https://github.com/libsdl-org/SDL_image/releases/download/release-2.6.3/SDL2_image-devel-2.6.3-VC.zip
          copy SDL2_image-2.6.3\lib\$Env:ARCH\*.lib C:\vcpkg\installed\$Env:ARCH-windows\lib
          copy SDL2_image-2.6.3\lib\$Env:ARCH\*.dll C:\vcpkg\installed\$Env:ARCH-windows\bin
          copy SDL2_image-2.6.3\include\*.h C:\vcpkg\installed\$Env:ARCH-windows\include\SDL2

      - name: Install SDL2_mixer
        working-directory: manual
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          C:\msys64\usr\bin\wget.exe https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.6.3/SDL2_mixer-devel-2.6.3-VC.zip
          copy SDL2_mixer-2.6.3\lib\$Env:ARCH\*.lib C:\vcpkg\installed\$Env:ARCH-windows\lib
          copy SDL2_mixer-2.6.3\lib\$Env:ARCH\*.dll C:\vcpkg\installed\$Env:ARCH-windows\bin
          copy SDL2_mixer-2.6.3\include\*.h C:\vcpkg\installed\$Env:ARCH-windows\include\SDL2

      - name: Configure bulid
        env:
          ARCH: ${{ matrix.arch }}
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          cmake --version
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022"                                             \
            -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake              \
            -DSDL2_IMAGE_INCLUDE_DIR=C:\vcpkg\installed\$Env:ARCH-windows\include\SDL2    \
            -DSDL2_IMAGE_LIBRARY=C:\vcpkg\installed\$Env:ARCH-windows\lib\SDL2_image.lib  \
            -DSDL2_MIXER_INCLUDE_DIR=C:\vcpkg\installed\$Env:ARCH-windows\include\SDL2    \
            -DSDL2_MIXER_LIBRARY=C:\vcpkg\installed\$Env:ARCH-windows\lib\SDL2_mixer.lib

      - name: Build
        working-directory: build
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
        run: |
          cmake --build . --config $Env:BUILD_TYPE

      - name: Package
        uses: actions/upload-artifact@v2
        with:
          name: "Brux-Windows-${{ matrix.arch }}-${{ matrix.build_type }}-binary"
          path: "build/${{ matrix.build_type }}"
